// client/src/utils/categoryData.js
export const categories = {
    "Electronics": ["Mobile Phone", "Laptop", "Tablet", "Headphones / Earbuds", "Charger / Power Bank", "Smartwatch", "USB Drive", "Camera", "E-reader", "Calculator", "Speaker", "Mouse", "Keyboard", "Gaming Console", "Other Electronics"],
    "Apparel": ["Jacket / Hoodie", "Sweater", "T-Shirt / Shirt", "Scarf / Shawl", "Cap / Hat", "Gloves", "Uniform", "Lab Coat", "Jeans / Trousers", "Dress / Skirt", "Tie", "Socks", "Belt", "Blazer", "Other Apparel"],
    "Books & Stationery": ["Textbook", "Notebook", "Novel", "Diary / Journal", "Pen / Pencil Case", "File / Folder", "Calculator", "ID Card Holder", "Stapler", "Highlighter / Marker", "Drafting Tools", "Paintbrushes", "Sketchbook", "Assignment / Notes", "Other Stationery"],
    "ID Cards & Documents": ["Student ID Card", "Driver's License", "Aadhaar Card", "PAN Card", "Passport", "Debit / Credit Card", "Library Card", "Certificates", "Report / Thesis", "Application Form", "Resume / CV", "Bus / Metro Pass", "Event Tickets", "Photographs", "Other Document"],
    "Keys": ["Room Key", "Vehicle Key (Car/Bike)", "Locker Key", "Keychain", "House Key", "Cabinet Key", "P.O. Box Key", "Electronic Key Fob", "Padlock Key", "Cycle Lock Key", "Keyring with multiple keys", "Office Key", "Drawer Key", "Safe Key", "Other Keys"],
    "Bags & Luggage": ["Backpack", "Laptop Bag", "Handbag / Purse", "Duffle Bag", "Tote Bag", "Wallet", "Suitcase", "Sling Bag", "Lunch Bag", "Gym Bag", "Drawstring Bag", "Briefcase", "Pouch", "Camera Bag", "Other Bag"],
    "Accessories": ["Watch", "Jewellery (Ring, Earring)", "Wallet", "Belt", "Sunglasses", "Hair Accessories", "Tie", "Cufflinks", "Brooch / Pin", "ID Card Holder", "Phone Case", "Laptop Sleeve", "Scarf", "Keychain", "Other Accessory"],
    "Personal Care": ["Makeup Bag / Pouch", "Lipstick / Lip Balm", "Hand Sanitizer", "Perfume / Deodorant", "Hairbrush / Comb", "Towel", "Sunscreen", "Face Mask", "Contact Lens Case", "Lotion / Cream", "Shampoo / Conditioner", "Soap", "Toothbrush / Toothpaste", "Wet Wipes", "Other Personal Care"],
    "Sports Equipment": ["Badminton Racket", "Tennis Racket", "Cricket Bat", "Ball (Cricket, Football, etc.)", "Shuttlecock", "Skateboard", "Yoga Mat", "Gym Gloves", "Helmet", "Water Bottle", "Jump Rope", "Frisbee", "Sports Shoes", "Swim Goggles", "Other Sports Gear"],
    "Musical Instruments": ["Guitar", "Keyboard / Synthesizer", "Violin", "Flute", "Ukulele", "Drumsticks", "Harmonica", "Instrument Case", "Metronome / Tuner", "Music Sheets / Book", "Cables / Adapters", "Microphone", "Tabla / Dholak", "Sitar", "Other Instrument"],
    "Medical Items": ["Medicine / Pills", "Inhaler", "First-Aid Kit", "Prescription", "Bandages", "Medical Report", "Thermometer", "Hearing Aid", "Retainer / Braces Case", "Crutches", "Sling / Brace", "Blood Sugar Monitor", "Eyedrops", "Ointment", "Other Medical Item"],
    "Eyewear": ["Spectacles / Glasses", "Spectacle Case", "Sunglasses", "Contact Lenses", "Contact Lens Case", "Reading Glasses", "3D Glasses", "Safety Goggles", "Swimming Goggles", "Designer Frames", "Lens Cleaning Cloth", "Clip-on Sunglasses", "Monocle", "Magnifying Glass", "Other Eyewear"],
    "Umbrellas": ["Compact / Folding Umbrella", "Classic / Stick Umbrella", "Golf Umbrella", "Bubble Umbrella", "Automatic Umbrella", "Windproof Umbrella", "Kids Umbrella", "Designer Umbrella", "Umbrella Cover", "Mini Umbrella", "Sun Umbrella (Parasol)", "Raincoat", "Poncho", "Waterproof Trousers", "Other Rain Gear"],
    "Containers": ["Water Bottle", "Lunch Box / Tiffin", "Coffee Mug / Tumbler", "Thermos / Flask", "Plastic Container", "Glass Jar", "Pencil Box", "Jewellery Box", "Small Case (e.g., for earbuds)", "Storage Box", "Cutlery Case", "Protein Shaker", "Pill Box", "Art Supply Box", "Other Container"],
    "Other": ["Toys / Games", "Sporting Goods", "Art / Craft Supplies", "Religious Items", "Gift / Souvenir", "Groceries", "Pet Accessories", "Cushion / Pillow", "Blanket", "Poster / Artwork", "Tools", "Photo Frame", "E-Cigarette / Vape", "Lighter", "Miscellaneous"]
};